apiVersion: v1
kind: Service
metadata:
  name: vprodb # service name
spec:
  selector:
    app: vprodb #label of pod
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  type: ClusterIP
