apiVersion: v1
kind: Service
metadata:
  name: vprocache01  # service name
spec:
  selector:
    app: vpromc # targeting pod
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP
