apiVersion: v1
kind: Service
metadata:
  name: vpromq01  # service name
spec:
  selector:
    app: vpromq01 # targeting pod
  ports:
  - port: 15672
    targetPort: vpromq01-port
    protocol: TCP
  type: ClusterIP
